version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=SportSphere;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    networks:
      - sportsphere-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - sportsphere-data:/var/opt/mssql
      - ./init-sample-data.sql:/scripts/init-sample-data.sql
    networks:
      - sportsphere-network
    restart: always
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr &
        sleep 30s &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -i /scripts/init-sample-data.sql &&
        tail -f /dev/null
      "
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

networks:
  sportsphere-network:
    driver: bridge

volumes:
  sportsphere-data: 